#!/bin/sh

set -e

if ! command -v fish > /dev/null; then
  echo Installing fish
  brew install fish
fi

echo Linking files
ln -s ~/.dotfiles/fish/fish ~/.config/fish
ln -s ~/.dotfiles/fish/omf ~/.config/omf
